CREATE DATABASE d8dev CHARACTER SET utf8 COLLATE utf8_general_ci;
CREATE DATABASE d8stage CHARACTER SET utf8 COLLATE utf8_general_ci;
CREATE DATABASE d8prod CHARACTER SET utf8 COLLATE utf8_general_ci;

CREATE USER '$d8user'@'localhost' IDENTIFIED BY '$d8password';

GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, INDEX, ALTER, CREATE TEMPORARY TABLES ON d8dev.* TO '$d8user'@'localhost';

GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, INDEX, ALTER, CREATE TEMPORARY TABLES ON d8stage.* TO '$d8user'@'localhost'; 

GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, INDEX, ALTER, CREATE TEMPORARY TABLES ON d8prod.* TO '$d8user'@'localhost';  
